### ISSUE TITLE
How about merging some form of this into nixpkgs?

### ISSUE THREAD

**Issue by happysalada** [nixerl/nixpkgs-nixerl#5]
I just found out about this, it looks great!

Did you consider merging it into nixpkgs? Perhaps a in a different namespace, or there might be something needed to make it work, but I definitely think that you are not the only one with that problem.

I understand that getting things merged in nixpkgs is long and tedious, if it's only that, I would love to try to help.

**Comment by philipstears** [comment]
Hi there! I've certainly no objection to it. There are a couple of reasons why I've not even tried to do so.

The first of those is just down to remaining nimble, Erlang releases are tagged fairly frequently, probably too frequently for something like nixpkgs to keep track of.

The second is that, in the main, nixpkgs operates a single version policy, with few exceptions. It doesn't seem likely that the core maintainers would want to make an exception for this case - especially when it adds over 200 versions of Erlang to the package set, which presumably would be a disproportionately large extra burden on hydra and the the CDN.

**Comment by happysalada** [comment]
I see your point.
While I think the first point can be circumvented, I agree that the second point is a non starter. I hadn't thought about this.
Thanks for providing this!
